spring:
  application:
    name: spring-lab

server:
  port: 8080

app:
  owner: Zhanerke
  group: IS-2407

  mail:
    from: no-reply@iitu.kz
    retry-count: 3
    timeout: 5s
    enabled: true

  upload:
    max-file-size: 10MB
    allowed-extensions:
      - pdf
      - docx
      - xlsx

logging:
  level:
    kz.iitu: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,env